<!DOCTYPE html>
<html lang="en">
<head>
    <title>Retryable-exception vs Non-Retryable-exception - StackSAGA</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="description" content="Introduction to stacksaga">
    <meta name="author" content="Mafei">
    <link rel="shortcut icon" href="../../favicon.ico">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700&display=swap" rel="stylesheet">

    <!-- FontAwesome JS-->
    <script defer src="../../../assets/fontawesome/js/all.min.js"></script>

    <!-- Plugins CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.2/styles/atom-one-dark.min.css">
    <link rel="stylesheet" href="../../../assets/plugins/simplelightbox/simple-lightbox.min.css">

    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="../../../assets/css/theme.css">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-LC0M1Q19EK"></script>
    <link rel="stylesheet" href="../../../assets/css/custom.css">

    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'G-LC0M1Q19EK');
    </script>

</head>
<body class="docs-page">
<header class="header fixed-top">
    <div class="branding docs-branding">
        <div class="container-fluid position-relative py-2">
            <div class="docs-logo-wrapper">
                <button id="docs-sidebar-toggler" class="docs-sidebar-toggler docs-sidebar-visible me-2 d-xl-none"
                        type="button">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <div class="site-logo"><a class="navbar-brand" href="/index.html"><img class="logo-icon me-2"
                                                                                       src="../../../assets/images/coderdocs-logo.svg"
                                                                                       alt="logo"><span
                        class="logo-text">Stack<span class="text-alt">SAGA</span></span></a></div>
            </div><!--//docs-logo-wrapper-->
            <div class="docs-top-utilities d-flex justify-content-end align-items-center">
                <div class="top-search-box d-none d-lg-flex">
                    <form class="search-form">
                        <input type="text" placeholder="Search the docs..." name="search"
                               class="form-control search-input">
                        <button type="submit" class="btn search-btn" value="Search"><i class="fas fa-search"></i>
                        </button>
                    </form>
                </div>

                <ul class="social-list list-inline mx-md-3 mx-lg-5 mb-0 d-none d-lg-flex">
                    <li class="list-inline-item"><a href="#"><i class="fab fa-github fa-fw"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a></li>
                </ul><!--//social-list-->
                <a href="https://doc.stacksaga.com" target="_blank"
                   class="btn btn-primary d-none d-lg-flex">DOC</a>
            </div><!--//docs-top-utilities-->
        </div><!--//container-->
    </div><!--//branding-->
</header><!--//header-->
<div>

    <div>
        <div class="container">
            <article class="docs-article" id="section-1">
                <header class="docs-header">
                    <h1 id="microservice-introduction" class="docs-heading">Exceptions
                    </h1>
                    <section class="docs-intro">
                        <p>

                            While some process is executed some errors can be happened without knowing. Those exceptions
                            are called as runtime exception. And some errors can be occurred upon the data that you
                            pass. All those exceptions can be divided into two parts upon the retry capability.
                        </p>
                        <h4>What is retry capability?</h4>
                        <p>
                            Just imagine make a request to the payment service to make the payment. But at the moment
                            the request can be failed for mainly two reasons. One, the passing data is incorrect or the
                            customer balance is insufficient to process the execution. And the second one is, the
                            request can't achieve the payment service due to a network issue or, although the request
                            goes to the payment service, a database connection failure of the payment service database
                            can be effected to the request failure. So, passing incorrect data or inefficient balanne
                            are not retryable, because although we retried the process again and again, the same error
                            gets occurred every time. Because the reason is stable. But think about the second
                            reason. If it had a network issue in short period of time, the issue will be fixed soon.
                            Then the process can be invoked as usual. Most of the time, This kind of errors can be
                            runtime exception ( Io base exceptions/ network exceptions.) Other than that there can have
                            many exception upon your use-case. The programmer is the responsible person who decide the
                            exception is retryable or not.
                        </p>
                        <h4>
                            Why we identify the retryable exception in stacksaga?
                        </h4>
                        <p>
                            Retryable exception are not happened regularly. those exceptions are not accepted. Those are
                            very rare. You know in the microservices' architecture the main process have set of sequence
                            processes. We can't say how many number of steps are there. It will depend on your use-case.
                            Just think the whole process consist of 20 sub processes. 15 of process have been
                            successfully executed and the 16-step gets failed due to an issue. Then framework stop the
                            process and start the compensation process. While processing the compensations, one of
                            compensations is failed due to a network issue. Compensation transactions are Not just like
                            process executions,compensations is must. (if the process execution is failed at some point,
                            the compensation process can be executed. But if the compensation is failed we have nothing
                            to do anymore. If there's a compensation error, The transaction will be terminated and the
                            transaction is marked as garbage transaction.) Before terminate the transaction the
                            framework should know the error is caused due to a retryable exception or non retryable
                            exception. If it's a retryable exception the framework will keep the transaction pending to
                            execute that atomic compensation transaction after connection is fixed. If the reason is a
                            non retryable exception, the transaction will be marked as a garbage transaction by the
                            framework. That's why the retryable exceptions should be identified and inform about to the
                            framework.
                        </p>
                    </section><!--//docs-intro-->
                </header>

                <h1 id="how-retry-works-in-the-revert-process">How retry compensation-execution in the StackSaga</h1>
                <section class="docs-intro">

                    <p>
                        you already know that the process-execution (to forward executions) can be failed due to some
                        exceptions.
                        but the compensation process can't be failed if it not a retryable
                        error. most probably the retryable error happens due to a network error. that means
                        after
                        fixing the network issue, the transaction can be invoked as usual from the point tha
                        transaction
                        was stopped due to the network error.
                    </p>
                    <p>
                        the execution can be happened in three ways in StackSaga.
                    </p>

                    <ol>
                        <li>
                            <p>
                                <b>As a scheduled task.</b>
                            </p>
                            <p>
                                you can configure what time that you want to invoke that kind of revert-stuck
                                transactions in
                                your application as <a target="_blank"
                                                       href="./../reference/configuration-properties.html">configurations</a>.
                            </p>
                        </li>
                        <li>
                            <p>
                                <b>As a manual invocation from the Admin Dashboard.</b>
                            </p>
                            <p>in this option, you can manually invoke your stuck transactions by using <a
                                    href="./../topics/stacksaga-admin-dashboard.html"
                                    target="_blank">StackSaga
                                Admin
                                Dashboard</a></p>
                        </li>
                        <li>
                            <p>
                                <b>As an invocation of the StackSaga circuit breaker.</b>
                            </p>
                            <p>
                                just think that while the compensation is being processed, one of compensation is
                                failed
                                because
                                of that a related service is not running that time. (there is no at least one
                                instance
                                is up and
                                running.)
                                then the compensation process can't be invoked anymore. then the process is stuck
                                and
                                waiting
                                for the invocation after fixing the network issue. <a
                                    href="./../topics/stacksaga-circuit-breaker.html">StackSaga
                                circuit
                                breaker</a> is a live minicam to be notified about the availability of all
                                configured
                                services.
                                in
                                this example, the
                                order-service is listening to the payment-service's , delivery-service's,
                                user-service's
                                instance
                                updates through StackSaga and instantly the service will be notified when each and
                                every
                                server
                                gets up.
                            </p>
                            <p>
                                See the image below, at the start, there is no any payment-service up and running.
                                After
                                a
                                while, one payment-service gets up. Due to the order-service and user-service is
                                listening to the
                                payment-service's server updates, all the order-service and user-service instances will
                                be notified
                                instantly about the
                                new
                                upped
                                payment-service. After that, the SEC checks the database to verify if there are some
                                stuck
                                transactions due to the payment-service's network issue. if there are transactions, the
                                SEC invoke that transaction as batch process. you can configure the <a
                                    href="./../reference/configuration-properties.html#batch-process-configuration-properties">batch
                                processing
                                configuration</a> in your application.
                            </p>

                            <img class="img-fluid"
                                 src="../../../assets/images/architecture/1.0/how-update-cb-in-stacksaga.gif"
                                 alt=""/>
                        </li>
                    </ol>
                </section>

            </article>

        </div>
    </div>
</div>
<!-- Javascript -->
<script src="../../../assets/plugins/popper.min.js"></script>
<script src="../../../assets/plugins/bootstrap/js/bootstrap.min.js"></script>


<!-- Page Specific JS -->
<script src="../../../assets/plugins/smoothscroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/highlight.min.js"></script>
<script src="../../../assets/js/highlight-custom.js"></script>
<script src="../../../assets/plugins/simplelightbox/simple-lightbox.min.js"></script>
<script src="../../../assets/plugins/gumshoe/gumshoe.polyfills.min.js"></script>
<script src="../../../assets/js/docs.js"></script>
</body>
</html> 

